### ISSUE TITLE
Preço nulo

### ISSUE THREAD

**Issue by FelipeSGAndrade** [devphaelmoraes/realty#2]
O preço não é obrigatório?

https://github.com/devphaelmoraes/realty/blob/292797aa3e60e0e46af6fd076cc5e9ef006aca8c/src/realty/domain/realty.spec.ts#L77-L84

**Comment by phaelmoraes** [comment]
hehe não lembro qual foi a viagem, mas corrigir em [#80ce672](https://github.com/devphaelmoraes/realty/commit/80ce672cd31c1464b709518d510eae30c5b37c7c)
